-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 22:17:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBTeh-kursa_darbs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBTeh-kursa_darbs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBTeh-kursa_darbs` DEFAULT CHARACTER SET utf8 ;
USE `DBTeh-kursa_darbs` ;

-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`lietotaji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`lietotaji` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `vards` VARCHAR(255) NULL,
  `uzvards` VARCHAR(255) NULL,
  `epasts` VARCHAR(255) NULL,
  `lietotajvards` VARCHAR(255) NULL,
  `parole` VARCHAR(255) NULL,
  `telefona_numurs` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`lomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`lomas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `loma` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`transportlidzekli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`transportlidzekli` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `kategorija` ENUM('B', 'C', 'D') NULL,
  `marka` VARCHAR(255) NULL,
  `gads` YEAR(4) NULL,
  `krasa` VARCHAR(255) NULL,
  `numura_zime` VARCHAR(255) NULL,
  `transportlidzeklicol` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`lietotajiem_ir_transportlidzekli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`lietotajiem_ir_transportlidzekli` (
  `lietotaji_ID` INT NOT NULL,
  `transportlidzekli_ID` INT NOT NULL,
  PRIMARY KEY (`lietotaji_ID`, `transportlidzekli_ID`),
  INDEX `fk_lietotaji_has_transportlidzekli_transportlidzekli1_idx` (`transportlidzekli_ID` ASC),
  INDEX `fk_lietotaji_has_transportlidzekli_lietotaji1_idx` (`lietotaji_ID` ASC),
  CONSTRAINT `fk_lietotaji_has_transportlidzekli_lietotaji1`
    FOREIGN KEY (`lietotaji_ID`)
    REFERENCES `DBTeh-kursa_darbs`.`lietotaji` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lietotaji_has_transportlidzekli_transportlidzekli1`
    FOREIGN KEY (`transportlidzekli_ID`)
    REFERENCES `DBTeh-kursa_darbs`.`transportlidzekli` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`marsruti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`marsruti` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `no_pilsetas_ID` INT NULL,
  `no_pilsetas_valstis_ID` INT NULL,
  `uz_pilsetas_ID` INT NULL,
  `uz_pilsetas_valstis_ID` INT NULL,
  `no_adrese` VARCHAR(255) NULL,
  `uz_adrese` VARCHAR(255) NULL,
  `izbrauksanas_laiks` DATETIME NULL,
  `iebrauksanas_laiks` DATETIME NULL,
  `cena` DECIMAL NULL,
  `brivas_sedvietas` INT NULL,
  `irIzpildits` TINYINT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`lietotajiem_ir_marsruti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`lietotajiem_ir_marsruti` (
  `lietotaji_ID` INT NOT NULL,
  `marsruti_ID` INT NOT NULL,
  PRIMARY KEY (`lietotaji_ID`, `marsruti_ID`),
  INDEX `fk_lietotaji_has_marsruti_marsruti1_idx` (`marsruti_ID` ASC),
  INDEX `fk_lietotaji_has_marsruti_lietotaji1_idx` (`lietotaji_ID` ASC),
  CONSTRAINT `fk_lietotaji_has_marsruti_lietotaji1`
    FOREIGN KEY (`lietotaji_ID`)
    REFERENCES `DBTeh-kursa_darbs`.`lietotaji` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lietotaji_has_marsruti_marsruti1`
    FOREIGN KEY (`marsruti_ID`)
    REFERENCES `DBTeh-kursa_darbs`.`marsruti` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`lietotajiem_ir_lomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`lietotajiem_ir_lomas` (
  `lietotaji_ID` INT NOT NULL,
  `lomas_ID` INT NOT NULL,
  PRIMARY KEY (`lietotaji_ID`, `lomas_ID`),
  INDEX `fk_lietotaji_has_lomas_lomas1_idx` (`lomas_ID` ASC),
  INDEX `fk_lietotaji_has_lomas_lietotaji1_idx` (`lietotaji_ID` ASC),
  CONSTRAINT `fk_lietotaji_has_lomas_lietotaji1`
    FOREIGN KEY (`lietotaji_ID`)
    REFERENCES `DBTeh-kursa_darbs`.`lietotaji` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lietotaji_has_lomas_lomas1`
    FOREIGN KEY (`lomas_ID`)
    REFERENCES `DBTeh-kursa_darbs`.`lomas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`valstis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`valstis` (
  `ID` INT NOT NULL,
  `nosaukums` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBTeh-kursa_darbs`.`pilsetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeh-kursa_darbs`.`pilsetas` (
  `ID` INT NOT NULL,
  `valstis_ID` INT NOT NULL,
  `nosaukums` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`, `valstis_ID`),
  INDEX `fk_pilsetas_valstis1_idx` (`valstis_ID` ASC),
  CONSTRAINT `fk_pilsetas_valstis1`
    FOREIGN KEY (`valstis_ID`)
    REFERENCES `DBTeh-kursa_darbs`.`valstis` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DBTeh-kursa_darbs`.`lomas`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBTeh-kursa_darbs`;
INSERT INTO `DBTeh-kursa_darbs`.`lomas` (`ID`, `loma`) VALUES (3, 'administrators');
INSERT INTO `DBTeh-kursa_darbs`.`lomas` (`ID`, `loma`) VALUES (2, 'soferis');
INSERT INTO `DBTeh-kursa_darbs`.`lomas` (`ID`, `loma`) VALUES (1, 'pasazieris');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DBTeh-kursa_darbs`.`valstis`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBTeh-kursa_darbs`;
INSERT INTO `DBTeh-kursa_darbs`.`valstis` (`ID`, `nosaukums`) VALUES (1, 'Estonia');
INSERT INTO `DBTeh-kursa_darbs`.`valstis` (`ID`, `nosaukums`) VALUES (2, 'Latvia');
INSERT INTO `DBTeh-kursa_darbs`.`valstis` (`ID`, `nosaukums`) VALUES (3, 'Lithuania');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DBTeh-kursa_darbs`.`pilsetas`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBTeh-kursa_darbs`;
INSERT INTO `DBTeh-kursa_darbs`.`pilsetas` (`ID`, `valstis_ID`, `nosaukums`) VALUES (1, 1, 'Tallinn');
INSERT INTO `DBTeh-kursa_darbs`.`pilsetas` (`ID`, `valstis_ID`, `nosaukums`) VALUES (2, 1, 'Tartu');
INSERT INTO `DBTeh-kursa_darbs`.`pilsetas` (`ID`, `valstis_ID`, `nosaukums`) VALUES (3, 2, 'Ventspils');
INSERT INTO `DBTeh-kursa_darbs`.`pilsetas` (`ID`, `valstis_ID`, `nosaukums`) VALUES (4, 2, 'Riga');
INSERT INTO `DBTeh-kursa_darbs`.`pilsetas` (`ID`, `valstis_ID`, `nosaukums`) VALUES (5, 2, 'Liepaja');
INSERT INTO `DBTeh-kursa_darbs`.`pilsetas` (`ID`, `valstis_ID`, `nosaukums`) VALUES (6, 3, 'Vilnius');
INSERT INTO `DBTeh-kursa_darbs`.`pilsetas` (`ID`, `valstis_ID`, `nosaukums`) VALUES (7, 3, 'Kaunas');

COMMIT;

